In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("call_center.csv")

In [21]:
df.head()

,Call Id,Date,Agent,Department,Answered (Y/N),Resolved,Speed of Answer,AvgTalkDuration,Satisfaction rating
0,ID0001,01-01-2015 9:12,Diane,Washing Machine,Y,Y,109.0,00:02:23,3.0
1,ID0002,01-01-2015 9:12,Becky,Air Conditioner,Y,N,70.0,00:04:02,3.0
2,ID0003,01-01-2015 9:47,Stewart,Washing Machine,Y,Y,10.0,00:02:11,3.0
3,ID0004,01-01-2015 9:47,Greg,Washing Machine,Y,Y,53.0,00:00:37,2.0
4,ID0005,01-01-2015 10:00,Becky,Toaster,Y,Y,95.0,00:01:00,3.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call Id              5000 non-null   object
 1   Date                 5000 non-null   object
 2   Agent                5000 non-null   object
 3   Department           5000 non-null   object
 4   Answered (Y/N)       5000 non-null   object
 5   Resolved             5000 non-null   object
 6   Speed of Answer      4054 non-null   float64
 7   AvgTalkDuration      4054 non-null   object
 8   Satisfaction rating  4054 non-null   float64
dtypes: float64(2), object(7)
memory usage: 351.7+ KB

In [5]:
df.shape

(5000, 9)

In [20]:
df = df.drop(['Unnamed: 9','Unnamed: 10'], axis = 1, inplace = False)

In [11]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.columns

Index(['Call Id', 'Date', 'Agent', 'Department', 'Answered (Y/N)', 'Resolved',
       'Speed of Answer', 'AvgTalkDuration', 'Satisfaction rating'],
      dtype='object')

In [24]:
df.dtypes

Call Id                 object
Date                    object
Agent                   object
Department              object
Answered (Y/N)          object
Resolved                object
Speed of Answer        float64
AvgTalkDuration         object
Satisfaction rating    float64
dtype: object

In [25]:
df.describe()

       Speed of Answer  Satisfaction rating
count      4054.000000          4054.000000
mean         67.520720             3.403552
std          33.592872             1.212220
min          10.000000             1.000000
25%          39.000000             3.000000
50%          68.000000             3.000000
75%          97.000000             4.000000
max         125.000000             5.000000

In [26]:
df["Speed of Answer"] = df["Speed of Answer"].fillna(0)

In [27]:
df["AvgTalkDuration"] = df["AvgTalkDuration"].fillna("00:00:00")

In [28]:
df["Satisfaction rating"] = df["Satisfaction rating"].fillna(0)

In [29]:
#Python Analysis (EDA)
#total number of calls
df.shape

(5000, 9)

In [30]:
#Total calls
len(df)

5000

In [31]:
#Total Agents
df["Agent"].unique()

array(['Diane', 'Becky', 'Stewart', 'Greg', 'Jim', 'Joe', 'Martha', 'Dan'],
      dtype=object)

In [32]:
#Call handled by each agent
df["Agent"].value_counts()  
#Business insights : Identifies which agent handled the most calls

Agent
Jim        666
Martha     638
Diane      633
Dan        633
Becky      631
Greg       624
Joe        593
Stewart    582
Name: count, dtype: int64

In [33]:
#Call by department
df["Department"].value_counts()
#Bussiness Insights: shows which department receives the highest cals

Department
Television         1022
Air Conditioner    1019
Toaster            1007
Washing Machine     976
Fridge              976
Name: count, dtype: int64

In [34]:
#Answered vs non answered
df["Answered (Y/N)"].value_counts()
#Bussiness Insights : percentage of answered and missed calls

Answered (Y/N)
Y    4054
N     946
Name: count, dtype: int64

In [35]:
#Resolved vs Unresolved calls
df["Resolved"].value_counts()
# Bussiness Insights : shows how effective the call center is at resolving customer issue

Resolved
Y    3646
N    1354
Name: count, dtype: int64

In [36]:
#Average speed of answer
df["Speed of Answer"].mean()
#Bussiness Insights : lower average speed means customer wait less

np.float64(54.7458)

In [37]:
df["AvgTalkDuration"].head(10)

0    00:02:23
1    00:04:02
2    00:02:11
3    00:00:37
4    00:01:00
5    00:00:00
6    00:03:40
7    00:00:38
8    00:06:38
9    00:01:04
Name: AvgTalkDuration, dtype: object

In [38]:
#converting it to time format before calculating average
df["AvgTalkDuration"] = pd.to_timedelta(df["AvgTalkDuration"])

In [39]:
#Average talk duration 
df["AvgTalkDuration"].mean()
#Bussiness Insights : helps understand how long agent speed with customers

Timedelta('0 days 00:03:02.367400')

In [40]:
#Average satisfication rating
df["Satisfaction rating"].mean()
#Bussiness Insights : measures overall customer satisfication

np.float64(2.7596)

In [41]:
#Highest satisfaction rating
df["Satisfaction rating"].max()

5.0

In [42]:
#Lowest satisfaction rating
df["Satisfaction rating"].min()

0.0

In [43]:
df.to_csv("cleaned_call_center.csv",index = False)